---
title: "Learning R Basics"
author: "Spencer Mathews"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
---



`distinct` / `duplicated?`

# Interactive Sessions

`sessionInfo()`


---

# Links


- [R Manuals](http://cran.r-project.org/manuals.html)
    - [An Introduction to R](http://cran.r-project.org/doc/manuals/r-release/R-intro.html)
    - [R Language Definition](http://cran.r-project.org/doc/manuals/R-lang.html), etc.


- [Hadley Wickham](http://had.co.nz/)
    - [Advanced R (Hadley Wickham)](http://adv-r.had.co.nz/)
    - [Courses Taught by Hadley Wickham](http://courses.had.co.nz/)


- [Gaston Sanchez](http://gastonsanchez.com/) has good stuff!


- [R Language for Programmers](http://www.johndcook.com/blog/r_language_for_programmers/)


- [RStudio Webinars](http://www.rstudio.com/resources/webinars/) [[GitHub](https://github.com/rstudio/webinars)]


- [Programming in R](http://manuals.bioinformatics.ucr.edu/home/programming-in-r) from [Bioconductor](http://manuals.bioinformatics.ucr.edu/home/R_BioCondManual)

- [The R Inferno](http://www.burns-stat.com/documents/books/the-r-inferno/) ([pdf](http://www.burns-stat.com/pages/Tutor/R_inferno.pdf))
- [Impatient R](http://www.burns-stat.com/documents/tutorials/impatient-r/)


- [R Pubs](http://rpubs.com/) is a place to publish and has good docs written by users


- [R Conferences](http://www.r-project.org/conferences.html)
    - [useR! 2014 @UCLA](http://user2014.stat.ucla.edu/)
    - [useR! 2013 @Spain](http://www.edii.uclm.es/~useR-2013/)
    - [useR! 2007 @Iowa State](http://user2007.org/)
    

- [Introduction to R Workshop (Ramnath Vaidyanathan @ Pycon 2015)](https://ramnathv.github.io/pycon2014-r/)


#### Tutorials

-  [Kelly Black's R Tutorial](http://www.cyclismo.org/tutorial/R/)


---

# Objects



# Data Types



typeof | mode | storage.mode
-------|------|-------------
logical | logical | logical
integer | numeric | integer
double | numeric | double
complex | complex | complex
character | character | character
raw | raw | raw


Learn about data types and more in [An Introduction to R](http://cran.r-project.org/doc/manuals/r-release/R-intro.html).

http://digitheadslabnotebook.blogspot.com/2010/01/r-type-system.html


- numeric
- character

vector

- list ("generic vector") An R list is an object consisting of an ordered collection of objects known as its components. There is no particular need for the components to be of the same mode or type.

    - `list()` 
    - `unlist()` flattens list, turning it into an atomic vector (with possible coercions like `c()`)


> Matrices and arrays are simply vectors with the attribute dim and optionally dimnames attached to the vector.

matrix

array

> An array in R can have one, two or more dimensions. It is simply a vector which is stored with additional attributes giving the dimensions (attribute "dim") and optionally names for those dimensions (attribute "dimnames").
>
> A two-dimensional array is the same thing as a matrix.


data frame

...

# Misc Functions

- 'length()`



# Objects and stuff

- `typeof()`
- `class()`
- `mode()`


- `str()` "Compactly display the internal structure of an R object, a diagnostic function and an alternative to summary"


`print()`


`is.atomic()`
...


### attributes

You can retrieve and assign attributes:

- `attributes()` - all attributes
- `attr()` - individually
- `mostattributes()`

Assign `NULL` to attributes to remove them.



# Booleans

all()


# Regular Expressions


## R Extended Regular Expressions

`[[:digit:]]`
`[[:alpha:]]`
etc.


grep/grepl


# Functions

- [Advanced R: Functions](http://adv-r.had.co.nz/Functions.html)



Call by value only!?


### Ellipses

`...` to allow for arbitrary number and variety of arguments and to pass on to other functions

- [How to use R's ellipsis feature](https://stackoverflow.com/questions/3057341/how-to-use-rs-ellipsis-feature-when-writing-your-own-function)
- [The three-dots construct in R](http://www.burns-stat.com/the-three-dots-construct-in-r/)



`.Primitive()`?



# Indexing

Read about indexing [here](http://cran.r-project.org/doc/manuals/r-release/R-lang.html#Indexing) and ...


`[[]]` vs `[]`...



# Manipulating Data Structures


- `c()` : more generic than append and can concatenate vectors or lists
- `append` : wraps c and allows for positional insertion with `after=` parameter.

Combine lists? c or append or what?


---

### Comparisons

`identical` is way too strict
`all.equal`

which !=

See `compare::compare()`.


[Comparing Data Frames](http://www.cookbook-r.com/Manipulating_data/Comparing_data_frames/)


### Sorting

`sort()` : sorting vectors or factors, can specify `decreasing=TRUE` to reverse.

`order()` : can sort along more than one variable (e.g. for tie breaking and data frames), see also `sort.list`.


`is.ordered()`


### Assertions

`stopifnot()` or see [assertthat](https://github.com/hadley/assertthat) package.


### Classes

S3 and S4 classes


### [Environments](http://cran.r-project.org/doc/manuals/R-lang.html#Environment-objects)

See a nice blog [post](http://blog.obeautifulcode.com/R/How-R-Searches-And-Finds-Stuff) about environments and scoping.

`ls()` has multiple uses!...
`rm()`
`objects()`



`new.env()`

`$`

`search()`
1. `globalenv()`
2. `environment()`
`parent.env()`

Links:
http://adv-r.had.co.nz/Environments.html
http://digitheadslabnotebook.blogspot.com/2011/06/environments-in-r.html

---

# Topics

### [Set Operations](https://stat.ethz.ch/R-manual/R-devel/library/base/html/sets.html)

1. `union`
2. `intersect`
3. `setdiff`
4. `setequal`
5. `is.element`

`choose()`

- `%in%` : is.element(x, y) is identical to x %in% y.


### Repetition and Permutation

See document on [Tricks](Tricks.html)

---

# Control Flow

`if` `else`


## Loops

http://paleocave.sciencesortof.com/2013/03/writing-a-for-loop-in-r/
http://rforpublichealth.blogspot.com/2013/01/for-loops-and-how-to-avoid-them.html
http://www.dummies.com/how-to/content/how-to-loop-through-values-in-r.html

`for`

```
for(i in values){
  ... do something ...
}
```

Or consider the apply family of functions:
http://www.dummies.com/how-to/content/how-to-apply-functions-on-rows-and-columns-in-r.html


---

# Constants

R has a small number of built-in constants:


- `LETTERS`: the 26 upper-case letters of the Roman alphabet;
- `letters`: the 26 lower-case letters of the Roman alphabet;
- `month.abb`: the three-letter abbreviations for the English month names;
- `month.name`: the English names for the months of the year;
- `pi`: the ratio of the circumference of a circle to its diameter.


---

# Help

`help()`

`apropose()` / `find()`

`search()`
`objects()`


