---
title: "Learn data frames"
author: "Spencer Mathews"
date: "`r Sys.Date()`"
output: html_document
---


`expand.grid()` - 
`combn`

`table` - contingency table




- `with()`
- `by()` applies to each level of factor


---



# Selecting Data

- By name: `my_dataframe$column_name` or `my_dataframe['column_name']`
- By index: `my_dataframe[index]` or range `my_dataframe[index1:index2]` 
- Note: Matrix notation (i.e. with comma) `my_dataframe[, 'column_name']` doesn't return data frame for single column!



# [Subsetting](http://adv-r.had.co.nz/Subsetting.html)


`subset()`
`split()`
`merge()`


Note: these may apply more broadly than data frames.

`cut()`
`split()`

`by`
`aggregate()`

`bin()`



# Factors

Factors can be unordered or [ordered](http://www.cookbook-r.com/Manipulating_data/Changing_the_order_of_levels_of_a_factor/).  Ordered factors impose an inequality among levels.

- `factor()` - create factor

- `ordered()` - create ordered factor

- `relevel()`

- `reorder()`

I believe that factors are by definition characters, so if you end up with numeric data as a factor then to convert to simple numeric values you do `as.numeric(as.character(myfactor))` or else you will end up with sequential integers reflecting the factor levels arbitrarily.