---
title: "Learn Statistics"
author: "Spencer Mathews"
date: "`r Sys.Date()`"
output: html_document
---

---

This will be a heavy document about doing statistics in R.  Since the two are almost synonymous, it will also be a chance to illustrate general statistical concepts.

# Statistics



## Links

- [R Tutorial (Statistics)](http://www.r-tutor.com)
- [Little Book of R for Multivariate Analysis!](https://little-book-of-r-for-multivariate-analysis.readthedocs.org/en/latest)
- [Handbook of Biological Statistics](http://www.biostathandbook.com) [[class](https://udel.edu/~mcdonald/statsyllabus.html)]
- Quick-R has sections on [Basic Statistics](http://www.statmethods.net/stats)
and [Advanced Statistics](http://www.statmethods.net/advstats)

- [Data Science with R](https://garrettgman.github.io/)



## Packages

- `stats` : the built in package
- [`corplot`](http://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html)
    - [](http://www.sthda.com/english/wiki/correlation-matrix-a-quick-start-guide-to-analyze-format-and-visualize-a-correlation-matrix-using-r-software)




## Model Formulae

http://www.dummies.com/how-to/content/how-to-use-the-formula-interface-in-r.html




---

---

# `stats` package



## Distributions

R has builtin support for many [distributions](https://stat.ethz.ch/R-manual/R-patched/library/stats/html/Distributions.html).

> The functions for the density/mass function, cumulative distribution function, quantile function and random variate generation are named in the form `dxxx`, `pxxx`, `qxxx` and `rxxx` respectively.


- `dnorm(x, mean = 0, sd = 1, log = FALSE)`
- `pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)` 
- `qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)`
- `rnorm(n, mean = 0, sd = 1)`


## Variance




- `var(x, y = NULL, na.rm = FALSE, use)`
- `cov(x, y = NULL, use = "everything", method = c("pearson", "kendall", "spearman"))`
- `cor(x, y = NULL, use = "everything", method = c("pearson", "kendall", "spearman"))`
- `cov2cor(V)`

- `symnum()` ?

See `corrplot` packages for visualization, including [`corrplot()`](http://www.sthda.com/english/wiki/visualize-correlation-matrix-using-correlogram) function and [`rquery.cormat()`](http://www.sthda.com/english/wiki/correlation-matrix-an-r-function-to-do-all-you-need) function.


And some good information about [correlation analysis](http://www.sthda.com/english/wiki/correlation).

- Pearson r : linear dependence
- Kendall tau : rank-based correlation coefficient
- Spearman rho : rank-base correlation coefficient


---

## Model Fitting


- `lm()` - linear model - `glm()` - generalized linear model

- `nls()` - nonlinear least squares


`base::summary()` give you info about the model you fitted.  Applied to data
frames it summarizes each column.


## _t_-Test

Berkeley has nice notes on [using t-tests in
R](http://statistics.berkeley.edu/computing/r-t-tests).

`t.test()` Performs one and two sample t-tests on vectors of data.
There is a standard and formula interface.


```
## Default S3 method:
t.test(x, y = NULL,
       alternative = c("two.sided", "less", "greater"),
       mu = 0, paired = FALSE, var.equal = FALSE,
       conf.level = 0.95, ...)
```

```
## S3 method for class 'formula'
t.test(formula, data, subset, na.action, ...)
```

- `formula`	a formula of the form lhs ~ rhs where lhs is a numeric variable giving the data values and rhs a factor with two levels giving the corresponding groups.


Returns

A list with class `htest` containing the following components:

- `statistic`	the value of the t-statistic.
- `parameter`	the degrees of freedom for the t-statistic.
- `p.value`	the p-value for the test.
- `conf.int` a confidence interval for the mean appropriate to the specified alternative hypothesis.
- `estimate` the estimated mean or difference in means depending on whether it was a one-sample test or a two-sample test.
- `null.value` the specified hypothesized value of the mean or mean difference depending on whether it was a one-sample test or a two-sample test.
- `alternative` a character string describing the alternative hypothesis.
- `method` a character string indicating what type of t-test was performed.
- `data.name`	a character string giving the name(s) of the data.



## Regressions


`poly()`/`polym()`


---

## Clustering


`dist()` - distance matrix

`hclust()` - has print(), plot(), identify functions


##Principal Component Analysis


- `princomp()`


---

---


# `MASS` package

## Discriminant Analysis

- `lda()` - `qda()`

- Thiago Martins on [Discriminant Analysis](https://tgmstat.wordpress.com/2013/12/04/discriminant-analysis) and [Computing and Visualizing LDA](https://tgmstat.wordpress.com/2014/01/15/computing-and-visualizing-lda-in-r)
- [Discriminant Analysis in R (RPubs by Gabriel Martos)](https://rpubs.com/gabrielmartos/discriminantR)

See also `dawai` packages.

