---
title: "Strings"
author: "Spencer Mathews"
date: "`r Sys.Date()`"
output: html_document
---


# Links

- [Handling and Processing Strings in R (by Gaston Sanchez)](http://gastonsanchez.com/Handling_and_Processing_Strings_in_R.pdf) Awesome PDF book!


### manipulation

`paste()`


### output


`print` returns the object whereas `cat` does not.  Print also by default adds a newline and also an output line number.  `cat` performs much less conversion" and" is not as object aware but not sure the consequences.

#### `cat()` 

> `cat` is useful for producing output in user-defined functions. It converts its arguments to character vectors, concatenates them to a single character vector, appends the given sep = string(s) to each element and then outputs them.


#### `print()`


`format()`





---

# `stringr` library


### seach

`grep`
`grepl`...


# Regular Expressions

> R supports two regular expression flavors: POSIX 1003.2 and Perl. Regular expression functions in R contain two arguments: extended, which defaults to TRUE, and perl, which defaults to FALSE. By default R uses POSIX extended regular expressions, though if extended is set to FALSE, it will use basic POSIX regular expressions. If perl is set to TRUE, R will use the Perl 5 flavor of regular expressions as implemented in the PCRE library. [[link](http://www.johndcook.com/blog/r_language_regex/)]

`[:digit:]` etc.

Link to a [talk](http://biostat.mc.vanderbilt.edu/wiki/pub/Main/SvetlanaEdenRFiles/regExprTalk.pdf).