---
title: "R Tricks"
author: "Spencer Mathews"
date: "`r Sys.Date()`"
output: html_document
---




`%in%`

`replicate()`


---





# Vs. Python

In Python you can use `in` in a for loop, but in R it is `%in%`.


---

# Subsetting

Atomic vectors can be subest using `[]` and positive integers, negative integers, logical operators, by names.

Using `[` to subset a list will always give a list, whereas `[[]]` (or `$`) allows you to pull out the components.

Subset matrix by `[,]` comma to separate dimensions.

Columns can be selected from data frames using matrix notation or list notation.  Note that when you only select a single column the matrix notation will simplify and not return a df!


---


# Combinatorics

How to generate combinations and permuations:


- `utils::combn()`

    `combn(x, m, FUN = NULL, simplify = TRUE, ...)`


- See also `combn()`, `combn2` and `permn()` in `combinat` package!
    
    `combn(x, m, fun=NULL, simplify=TRUE, ...)` `combn2(x, n) `


- `gtools::combinations()` / `gtools::permuations()` enumerates the possible combinations or permuations of a specified size from the elements of a vector

    Both have same parameters `combinations(n, r, v=1:n, set=TRUE, repeats.allowed=FALSE)`.
    
- There is also `caTools::combs()` but it may be redundant


`unique()`

`dplyr::distinct()`

`choose()` returns binomial coefficient

`outer()`


