---
title: "Learn dplyr"
author: "Spencer Mathews"
date: "`r Sys.Date()`"
output: html_document
---


Dplyr lets you omit quotes when referencing stuff, but there are functions which _end with underscores_ which take quoted strings and are suitable for using programmtically (may be useful to use `quote()`, `""`, or `~`)

Do not use meaningful row names with dplyr since they are not guaranteed to be preserved.



dplyr build around five verbs:

1. `select` certain columns of data.
2. `filter` your data to select specific rows.
3. `arrange` the rows of your data into an order.
4. `mutate` your data frame to contain new columns.
5. `summarise` chunks of you data in some way.


other functions:

- `glimpse`


# Objects

### tbl

`tbl_df()` makes for nicer print with no? side effects.
vs?
[`data_frame()`](http://cran.r-project.org/web/packages/dplyr/vignettes/data_frames.html)






# Working With Rows

### `filter()`

Many dplyr functions conserve attributes, but filter seems to lose them.

### `arrange()`

### `distinct()`
commonly used as distinct(select(...)) to find uniqe, similar to `base::unique`.



# Working With Columns


### `select()/rename()`

Note that if you're grouped the grouping variable stays around!

There are a number of convenience functions you can use in select, including `everything()`.

`num_range()` lets you select with "X" or other prefix

### `mutate()/transmute()`


### `summarise()`



---

# Grouping

Grouping a data frame by the value of a specified variable allows for the 

### `group_by()`

Call `groups()` to query the grouping variables, and `ungroup()` is obvious.
Grouping variable is stored in `vars` attribute.


`.dots`... `as.symbol/as.name`


### `summarise_each()`

Species functions including `n()`...


### `mutate_each`

### `tally()/count()`



---

# Manipulations


## `join_*`
~`base::merge`

It seems that join operations lose any attributes added by the user!!!


[Hadley:Two-table verbs](https://rpubs.com/hadley/45044)

If matches aren't exact generates Cartesian product.

### matching joins

#### `inner_join(x, y)` only includes observations that match in both x and y.

#### `full_join()` includes all observations from x and y.

#### `left_join(x, y)` includes all observations in x, regardless of whether they match or not. This is the most commonly used join because it ensures that you don't lose observations from your primary table.

#### `right_join(x, y)` includes all obserations in y. It's equivalent to left_join(y, x), but the columns will be ordered differently.


### filtering joins

These only ever remove observations.

#### `semi_join(x, y)` return all observations in x that have a match in y.
Like a left_join but nothing from b gets in a.

#### `anti_join(x, y)` return all observaitons in x that don't have a match in y.

### `bind_rows()/bind_cols()`
~rbind/cbind?!

bind_rows(x, ...)

bind_cols(x, ...)

combine(x, ...) ~ c() and unlist()


---

# `lazyeval`

[nse](http://cran.r-project.org/web/packages/dplyr/vignettes/nse.html)! non standar evaluation

Using `interp`, quote, eval I was able to feed variables into facet_grid.

Also see [this](http://adv-r.had.co.nz/Computing-on-the-language.html) and [this](http://adv-r.had.co.nz/Expressions.html).


---


# `magrittr`

`%>%` pipe function



