---
title: "shiny"
author: "Spencer Mathews"
date: "`r Sys.Date()`"
output: html_document
---



? come conditionalPanel examples using `===`, I think the condition needs to be in javascript!



# Links

- [Shiny Homepage](http://shiny.rstudio.com/)
    - [Shiny Tutorial](http://shiny.rstudio.com/tutorial/)
    - [Shiny Articles](http://shiny.rstudio.com/articles/)
        - [Introduction to R Markdown](http://shiny.rstudio.com/articles/rmarkdown.html)
        - [Introduction to interactive documents](http://shiny.rstudio.com/articles/interactive-docs.html)
- R Markdown Homepage
    - [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html)
    - [Embedded Shiny Apps](http://rmarkdown.rstudio.com/authoring_embedded_shiny.html)
    - [Creating Shiny Widgets](http://rmarkdown.rstudio.com/authoring_shiny_widgets.html)
    - [Interactive Documents: Advanced Topics](http://rmarkdown.rstudio.com/authoring_shiny_advanced.html)


https://shinydata.wordpress.com/2015/02/02/a-few-things-i-learned-about-shiny-and-reactive-programming/


# Basics

Interactive Inputs and Outputs.



When do you have to explicitely wrap in `reactive()`?



# Shiny Apps

`server.R` (defines `shinyServer()`)and `ui.R` (defines `shinyUI()`) or combiner server and UI in a single `app.R`
You can also use a `global.R` but probably not necessary.





## `server.R`

minimal = `shinyServer(function(input, output) {})`

- `input$<component_name>` to define _R components_ so you can use these objects in UI
    - since input values are reactive they must be surrounded by `render*`, `reactive`, `observe`, or `isolate`.
- `output$<widget_name>` to refer to widget values

`observe()`? `isolate()` in observe?


`render* function` | `*Output function`
-------------------|-----------------
`renderDataTable` | `dataTableOutput`
`renderImage` | `imageOutput`
`renderPlot` | `plotOutput`
`renderPrint` | `verbatimTextOutput`
`renderTable` | `tableOutput`
`renderText` | `textOutput`
`renderUI` | `htmlOutput` (`uiOutput` is just alias)






## `ui.R`

See [tutorial lesson 2](http://shiny.rstudio.com/tutorial/lesson2/)

minimal = `shinyUI(fluidPage())`






# Layouts

> titlePanel and sidebarLayout are the two most popular elements to add to fluidPage. They create a basic Shiny app with a sidebar.  sidebarLayout always takes two arguments:sidebarPanel function output mainPanel function output

> titlePanel and sidebarLayout create a basic layout for your Shiny app, but you can also create more advanced layouts. You can use navbarPage to give your app a multi-page user-interface that includes a navigation bar. Or you can use fluidRow and column to build your layout up from a grid system. 


See the [Layout Guide](http://shiny.rstudio.com/articles/layout-guide.html).


tabsetPanel() and navlistPanel()



# Inputs

Read about control widgets in [Tutorial 3](http://shiny.rstudio.com/tutorial/lesson3/).

The first argument to Input functions is a a string name.  The input is referenced in the Outputs as `input$<name>`

`selectInput()` - widget
some ideas for creating selections from a data frame are `unique()` and `setNames()` or `updateSelectInput()`.

`sliderInput()` - widget

`numericInput()`


`inputPanel()` - put widgets in here



# Outputs

Needs `({})` syntax.


- `renderImage`   images (saved as a link to a source file)
- `renderPlot` 	plots
- `renderPrint` 	any printed output
- `renderTable` 	data frame, matrix, other table like structures
- `renderText` 	character strings
- `renderUI` 	a Shiny tag object or HTML

`plotOutput`??

For reactive interfaces use `renderUI` (... use for reactive interfaces)



# Functions

`shinyApp` looks like it has functions `ui`, `server`, and `options` as paramters.
`options = list(height = 500)` sets default height of widget when rendered inside document.



`isolate()` - can help performance


# UI

`fluidPage()` 
containing `fluidRow()` which contains `column`, `plotOutput`, etc.

`sidebarLayout()` containing `sidebarPanel()`.


## Tabbed Layout


---


# Tips and Tricks


Look [here](http://shiny.rstudio.com/reference/shiny/latest/imageOutput.html) for a place to start about mouse interaction in plots.





---

# R Markdown and Widgets

Inputs and Outputs can also be also be embedded in R Markdown (specify `runtime: shiny`).

They may be used directly in code chunks or a Shiny App may be embedded by calling `shinyApp()` or a function which wraps it, or `shinyAppDir()`.

The demo for embedding Shiny in R Markdown puts controls in `inputPanel()`

### `shinyApp()`

Used to create Shiny widgets, you pass `ui` and `server`.


When you use `runtime::shiny` then rendering is done as you had explicitely called:
`rmarkdown::run("myfile.Rmd")`         # Frame not visible
The other options that seems to underlie when you don't have interactive is:
`rmarkdown::render("myfile.Rmd")`      # Frame visible


Best practices to use `fluidPage` with `responsive = FALSE` so when widget gets smaller its elements shrink instead of wrap.
Also on `plotOutput` as well as the `renderPlot(..., height=400)` set plot to 400 to leave room for controls.



---

# Deploy

1. Host on [shinyapps.io](https://www.shinyapps.io)

Shiny Apps and interactive documents can both be deployed on shinyapps using R Studio or the `shinyappsdeployApp()` function.

2. Run from R

`runGitHub("user/repo")`

`runURL()`
