---
title: "XML Packages"
author: "Spencer Mathews"
date: "`r Sys.Date()`"
output: html_document
---

---

# Links

###### primary links

- [XML Package (CRAN)](http://cran.r-project.org/package=XML)
- [xml2 (CRAN)](http://cran.r-project.org/package=xml2) [[GitHub](https://github.com/hadley/xml2)]

###### learning

- [Parse and process XML (and HTML) with xml2](http://blog.rstudio.org/2015/04/21/xml2/)
- [Basics of XML and HTML \@gastonsanchez](http://gastonsanchez.com/work/webdata/getting_web_data_r3_basics_xml_html.pdf)
- [Parsing XML/HTML Content \@gastonsanchez](http://gastonsanchez.com/work/webdata/getting_web_data_r4_parsing_xml_html.pdf)
- [R and the web (for beginners), Part II: XML in R](http://giventhedata.blogspot.com/2012/06/r-and-web-for-beginners-part-ii-xml-in.html)


---

XML Definitions
---------------


# Tasks

## Parsing XML

## Parsing HTML

Read HTML file by `xml2::read_html()`

---

# XML Package

### Objects

###### Documents

`XMLInternalDocument` (C-level)
`XMLDocument` (R-level)
`HTMLInternalDocument` (C-level)
`XMLDocumentContent` (R-level)

###### Other

`XMLNode`


### Reading XML

`xmlParse()` returns C-level `XMLInternalDocument` by default but if `useInternalNodes = FALSE` then returns R-level `XMLDocument` which is hierarchy of lists.  `xmlTreeParse()` is a convenient wrapper to do this.  `xmlParse()` only works on well formed XML documents.

You can parse HTML using `xmlParse` with `isHTML=TRUE` (or equivalently `htmlParse()`) which yields `HTMLInternalDocument`, or with `useInternalNodes = FALSE` (or just `htmlTreeParse()`) which yields `XMLDocumentContent.

- `xmlParse()`
- `xmlTreeParse()`
- `htmlParse()`
- `htmlTreeParse()`


See `asText=` argument when parsing.

## Tree Manipulation

- `xmlRoot()`
- `xmlChildren()`


## Node Manipulation

- `xmlName()` name of the node
- `xmlSize()` number of subnodes
- `xmlAttrs()` named character vector of all attributes
- `xmlGetAttr()` value of a single attribute
- `xmlValue()` contents of a leaf node
- `xmlParent()` name of parent node
- `xmlAncestors()` name of ancestor nodes
- `getSibling()` siblings to the right or to the left
- `xmlNamespace()` the namespace (if there’s one)


## ...

`xmlApply()`
`xmlSApply()`

`getNodeSet()` uses XPath to query 

`xpathApply()`/`xpathSApply()`


`readHTMLTable()`...



---

# `xml2` package

Newer and nicer but not as powerful as `XML`.

- `xml_document`
- `xml_node`?
- `xml_nodeset`


I think you can start working on the root directly.


I'm still figuring out XML namespaces, but when you read in XML with `read_xml()` you can get the `xml_namespace` object using the `xml_ns()` function. An `xml_namespace` object can contain multiple names, with `d1`, `d2`, etc. being the defaults.  You can (and should in order to use `xml_find_all()` to find things in a namespace) rename namespace objects with `xml_ns_rename(ns, d1 = "newname1", d2 = "newname2")`

`xml_name()` returns the name (tag) of an xml element, but you can give a namespace as the second parameter and use fully qualified names.  Also for `xml_find_all()`.

`xml_find_all()` won't work to find things in a namespace unless you provide the second ns parameter.


## Classes

- `xml_nodeset`
- `xml_namespace`
...

## Functions

###### reading
- `read_xml()`
- `read_html()` : calls `read_xml()` with `as_html = TRUE`

###### namespaces
- `xml_ns()`
- `xml_ns_rename()`

###### navigation
- `xml_children()` 
- `xml_siblings()`
- `xml_parent()`
- `xml_contents()`

- `xml_find_one()` and `xml_find_all()` use xpath to find nodes of interest
- `xml_path()` get the full path to a node

###### node information
- `xml_text()`
- `xml_attrs()`
- `xml_attr()`
- `xml_name()`

###### urls
- `url_absolute()` convert relative urls to absolute
, and transform in the opposite direction with 
- `url_relative()` transform absolute urls to relative

###### misc
- `xml_structure()`
- `as_list()` convert to list
- `url_escape()` and `url_unescape()` escape and unescape special characters

> Where appropriate, functions support namespaces with a global url -> prefix lookup table. See `xml_ns()` for more details.

> Support for modifying and creating xml documents in planned in a future version.


---

# XPATH

- `//`  finds anywhere in the document (ignoring the current node)
- `.//` finds anywhere beneath the current node

`xml_find_all(x, ".//term")`
